# Generated by Django 4.1.3 on 2022-12-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='desc',
            new_name='descrip',
        ),
    ]
